Repository TheLocehiliosan/yadm, pull requests merged in 2021-02, with the labels that each got.

#310 Update 060_alternates.md, fix MacBook typo
  _docs/060_alternates.md
Labels: documentation

#308 Add OS note for Cygwin/MinGW
  _docs/060_alternates.md
Labels: documentation

#301 Support passing relative paths to --yadm-*
  test/test_init.py
  test/test_unit_configure_paths.py
  yadm
  yadm.1
Labels: enhancement

#303 Tighten up parsing of if-statement in default template
  yadm
Labels: enhancement

#306 Add 'shellcheck shell=bash' as the default
  yadm
Labels: enhancement

#307 Simplify parse_encrypt by exiting early
  yadm
Labels: enhancement

#311 Fix typo in test (can_upgraded_... -> can_upgrade_...)
  test/test_upgrade.py
Labels: bug

#317 Replace cats with reads (passes all tests)
  yadm
Labels: enhancement
